services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: samir
      POSTGRES_PASSWORD: samir
      POSTGRES_DB: todos
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
